## Exercise 1
#### The following two-dimensional array is given:

A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1


#### Split this array into three parts:

- the first two columns assign to the A1 variable

- the next four columns assign to the A2 variable

- the last two columns assign to the A3 variable

#### In response, print these arrays to the console as shown below.

Tip: Use the function np.split().

In [3]:
import numpy as np


np.random.seed(42)

A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1

A1, A2, A3 = np.split(A, [2, 6], axis=1)
print(A1)
print(A2)
print(A3)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[4 6 2 4]
 [6 2 2 4]
 [1 3 5 5]
 [3 1 5 4]
 [2 6 1 3]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


#### Notes:


- The numpy.split() function in NumPy is used to split an array into multiple sub-arrays. This function has several variations depending on how you want to split the array. Here’s a basic overview of its syntax and usage:

- The array you want to split.
- indices_or_sections: This can be an integer or a 1-D array.
    - If it's an integer, it determines the number of equal parts the array will be split into.
    - If it's an array, it specifies the points where the split will occur.
- axis: The axis along which to split the array. By default, it is 0 (the first axis).

## Exercise 2
#### The following array is given:

A = np.random.randint(low=0, high=2, size=(10, 6))

#### Calculate the total number of non-zero elements in this array and print it to the console.

Tip: Use the np.count_nonzero() function.

In [4]:
np.random.seed(42)

A = np.random.randint(low=0, high=2, size=(10, 6))

print(np.count_nonzero(A))

31


#### Note:

- The np.count_nonzero() function in NumPy counts the number of non-zero elements in an array. It can operate on the entire array or along a specific axis. This function is useful for quickly determining how many non-zero elements are present in the data.

## Exercise 3
#### The following array is given below:

A = np.random.randn(10, 4)

#### Set the Numpy option to print arrays with specified precision. Set precision to 4 and print this array.

In [9]:
np.random.seed(42)

A = np.random.randn(10, 4)

np.set_printoptions(precision =4)

print(A)

[[ 0.4967 -0.1383  0.6477  1.523 ]
 [-0.2342 -0.2341  1.5792  0.7674]
 [-0.4695  0.5426 -0.4634 -0.4657]
 [ 0.242  -1.9133 -1.7249 -0.5623]
 [-1.0128  0.3142 -0.908  -1.4123]
 [ 1.4656 -0.2258  0.0675 -1.4247]
 [-0.5444  0.1109 -1.151   0.3757]
 [-0.6006 -0.2917 -0.6017  1.8523]
 [-0.0135 -1.0577  0.8225 -1.2208]
 [ 0.2089 -1.9597 -1.3282  0.1969]]


#### Note:

The function np.set_printoptions() in NumPy is used to control the way arrays are printed. The parameter precision specifies the number of digits of precision for floating-point output and suppress, whether or not suppress printing of small floating-point values using scientific notation (default is False).

## Exercise 4

#### The following array is given:

A = np.array([1.2e-6, 1.7e-7])

#### Set the precision to 8 and also set the appropriate Numpy option to suppress mathematical notation and print this array to the console.

In [13]:
A = np.array([1.2e-6, 1.7e-7])

np.set_printoptions(precision = 8, suppress = True)

print(A)

[0.0000012  0.00000017]
