## Exercise 1

#### Check which numbers (element-wise) from the A array are greater than numbers from the B array and print result to the console as shown below.

In [1]:
import numpy as np


A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])

In [2]:
print(np.greater(A,B))

[ True False False False]


#### Note:
The np.greater() function in NumPy is used to perform element-wise comparison between two arrays. It returns a boolean array where each element is True if the corresponding element in the first array is greater than the corresponding element in the second array, and False otherwise.

## Exercise 2
#### Using Numpy create a 4x4 array filled with zeros (set data type to int). In response print this array to the console.

In [4]:
array = np.zeros((4, 4), dtype = int)
print(array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


#### Note:
The np.zeros() function in NumPy is used to create a new array filled with zeros. The array can have any shape and data type specified by the user.

## Exercise 3
#### Using Numpy, create an array 10x10 filled with number 255 and set the data type to float. Print this array to the console as shown below.

In [5]:
array2 = np.full((10,10), 255, dtype=float)
print(array2)

[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]]


#### Note:
The np.full() function in NumPy creates a new array of the specified shape and data type, filled with a specified value.