## Exercise 1
#### The following array (square matrix) is given:

#### Calculate eigenvalues and their corresponding eigenvectors of this matrix and print to the console as shown below.

Tip: Use the np.linalg.eig() function.

In [2]:
import numpy as np

A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])

eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[-9.24621125 -3.          7.24621125]
[[-6.26164716e-01 -8.94427191e-01  8.90159406e-01]
 [-3.13082358e-01  3.52999668e-17  4.45079703e-01]
 [ 7.14070855e-01  4.47213595e-01 -9.75719719e-02]]


#### Note: 

- np.linalg.eig() is a function in the NumPy library used to compute the eigenvalues and right eigenvectors of a square matrix.

## Exercise 2
#### The following array (square matrix) is given:

#### Find the inverse matrix to this matrix and print it to the console.

Tip: Use the np.linalg.inv() function.

In [3]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])

print(np.linalg.inv(A))

[[-0.21393035  0.75621891  0.23880597]
 [ 0.05970149  0.04477612  0.11940299]
 [ 0.09950249 -0.25870647 -0.13432836]]


#### Note:

- np.linalg.inv() is a function in the NumPy library used to compute the inverse of a square matrix. The inverse of a matrix 𝐴 is another matrix, denoted as 𝐴−1, such that when A is multiplied by 𝐴−1, it results in the identity matrix.

## Exercise 3
#### The following array (square matrix) is given:
#### Find the trace of this matrix (sum of elements on the main diagonal) and print result to the console.

Tip: Use the np.trace() function.

In [5]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])

E3 = np.trace(A)

print(E3)

-5


#### Note:

- np.trace() is a function in the NumPy library used to compute the trace of a matrix. The trace of a matrix is the sum of the elements on its main diagonal (the diagonal that runs from the top-left to the bottom-right).

- numpy.trace(a, offset=0, axis1=0, axis2=1, dtype=None, out=None)

- Parameters:
    - a: Input array, from which the trace is computed.
    - offset: int, Offset of the diagonal from the main diagonal. Default is 0.
        - offset=0: main diagonaloffset > 0: diagonals above the main diagonal
        - offset < 0: diagonals below the main diagonal
    - axis1, axis2: int, optional 
        - Axes to be used as the first and second axis of the 2-D sub-arrays from which the diagonals should be taken. By default, the last two axes are used.
    - dtype: data-type, optional.
        - Determines the data-type of the returned array and of the accumulator where the elements are summed. By default, the dtype of a is used.
    - out: ndarray, optional
        -Alternative output array in which to place the result. It must have the same shape and buffer length as the expected output.

## Exercise 4
#### The following arrays are given:


#### Transform B array to perform the matrix multiplication A x B. Then perform this multiplication and print result to the console.

In [10]:

A = np.array([[2, 0],
              [4, 2],
              [5, 3],
              [4, 2]])
B = np.array([[4, 0, 2, 1, 1, 0, 2, 9]])

B1 = np.array(B).reshape(2,-1)

E4 = np.dot(A, B1)

print(E4)

[[ 8  0  4  2]
 [18  0 12 22]
 [23  0 16 32]
 [18  0 12 22]]


#### Note:

- This expression reshapes the array B into a 2xN array, where N is automatically calculated based on the size of B. The -1 in the reshape function allows NumPy to automatically determine the number of columns needed, given that the reshaped array has 2 rows.