## Exercise 1
#### The following arrays are given:

A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')


#### Check the Pythagorean formula for sines and cosines on the A array and then compare the result with the B array. Use the np.allclose() function in this exercise.

#### In response, print result to the console.



In [2]:
import numpy as np


A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')

print(np.allclose(np.sin(A) ** 2 + np.cos(A) ** 2, B))

True


#### Notes:

- np.sin(A) ** 2 + np.cos(A) ** 2 computes the element-wise sum of the squares of the sine and cosine of each element in A.

- np.allclose(..., B) checks if this result is element-wise equal to the array B, within a certain tolerance.

## Exercise 2
#### The following arrays are given:


#### Perform matrix multiplication A x B and print result to the console.

Tip: Use the np.dot() function.

In [3]:
A = np.array([[2, 3],
              [-4, 2],
              [5, 0]])
B = np.array([[4, 3, 2],
              [-1, 0, 2]])

E2 = np.dot(A, B)

print(E2)

[[  5   6  10]
 [-18 -12  -4]
 [ 20  15  10]]


#### Notes:


- The np.dot() function in NumPy computes the dot product of two arrays. For 2-D arrays, this is equivalent to matrix multiplication.

## Exercise 3
#### The following array (square matrix) is given:

A = np.array([[-2, 0, 4],
              [5, 2, -1],
              [-4, 2, 4]])


#### Calculate the determinant of this matrix and print it to the console.

Tip: Use the np.linalg.det() function.

In [5]:
A = np.array([[-2, 0, 4],
              [5, 2, -1],
              [-4, 2, 4]])

E3 = np.linalg.det(A)

print(E3)

51.999999999999986


#### Note:

- np.linalg.det() is a function in the NumPy library used to compute the determinant of a square matrix. 