## Exercise 1
#### The following array is given:

A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

#### Using Numpy create an array of the same shape and data type as the given array and fill it with a constant value = 9.99. Print this array to the console.

Tip: Use the np.full_like() function.

In [1]:
import numpy as np

A = np.array([[4.99, 3.49, 9.99], 
              [1.99, 9.99, 14.99], 
              [14.99, 2.39, 7.29]])

E1 = np.full_like(A, 9.99)

print(E1)

[[9.99 9.99 9.99]
 [9.99 9.99 9.99]
 [9.99 9.99 9.99]]


#### Note:

- The np.full_like is used to create a new array with the same shape and type as a given array, but filled with a specified value. This function is useful when you want to initialize an array that matches the dimensions and type of another array but with a uniform value.


- np.full_like(a, fill_value, dtype=None, order='K', subok=True, shape=None)

## Exercise 2
#### Using Numpy create a two-dimensional array (lower triangular matrix):

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

#### In response, print result to the console.

Tip: Use the np.tri() function.

In [2]:
E2 = np.tri(5, 5, k=0)
print(E2)

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


#### Note:

The np.tri function in NumPy is used to create a triangular matrix, which is a matrix where all the elements above (or below) the main diagonal are zero

## Exercise 3
#### Using Numpy create any 3-dimensional array with shape (2, 3, 4) and assign to variable A.

In [8]:
A = np.arange(24).reshape(2,3,4)
print(A)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## Exercise 4
#### Using Numpy create a two-dimensional array with shape of (200, 300) filled with random values from 0 to 255 (inclusive) with data type np.uint8.

In [9]:
E4 = np.random.randint(0, 255, (200,300), np.uint8)
print(E4)

[[ 32 176 101 ...  73  23 245]
 [161 213 250 ... 249 232 176]
 [123  77 187 ... 178 194 111]
 ...
 [211 125 238 ...  54 105 162]
 [152 116 239 ...  96 171  48]
 [107   4   3 ...  32  14 219]]


#### Note:

- The np.random.randint function in NumPy is used to generate an array of random integers within a specified range. This function is particularly useful for creating arrays of random integers for simulations, testing, and other applications that require random data.

- np.random.randint(low, high=None, size=None, dtype=int)