## Exercise 1
#### Using Numpy create a one-dimensional array of all two-digit numbers and print this array to the console as shown below.

In [4]:
import numpy as np

array = np.arange(10, 100, 1, dtype=int)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


#### Note:
The np.arange() function in NumPy generates an array with evenly spaced values within a specified range.

## Exercise 2
#### Using Numpy change the format of the previous array to (9,10)

In [5]:
array2 = np.ndarray.reshape(array, (9,10))
print(array2)

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


## Note:
The np.ndarray.reshape() method in NumPy is used to change the shape of an existing array without changing its data.

## Exercise 3
#### Using Numpy create a 6x6 two-dimensional array - identity matrix with int data type. Print this array to the console as shown below.

In [7]:
array3 = np.eye(6, 6, dtype=int)
print(array3)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


#### Note:
The np.eye() function in NumPy creates a 2-D array with ones on the diagonal and zeros elsewhere, essentially creating an identity matrix.