## Exercise 1
#### The following array is given:

A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])
              
#### Extract all unique values of this array as a list and print it to the console.

Tip: Use the np.unique() function.

In [1]:
import numpy as np

A = np.array([[5, 1, 2, 1, 2], [9, 1, 9, 7, 5], [4, 1, 5, 7, 9]])

print(np.unique(A))

[1 2 4 5 7 9]


#### Note:

The np.unique() function in NumPy is used to find the unique elements of an array. It can also provide additional information about the unique elements, such as their counts and indices.

## Exercise 2
#### The following array is given:

A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])


#### Return a list of indexes with maximum values for each row from this array and print it to the console.

Tip: Use the np.argmax() function.

In [5]:
A = np.array([[0.4, 0.3, 0.3], [0.1, 0.1, 0.8], [0.2, 0.5, 0.3]])

print(np.argmax(A, axis = 1))

[0 2 1]


#### Note:

The np.argmax() function in NumPy is used to find the index of the maximum value in an array. It can be applied to both 1-dimensional and multi-dimensional arrays.

## Exercise 3
#### The following array is given:

A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

#### Sort this array: by row (ascending), by column (ascending), and print result to the console as shown below.

Tip: Use the np.sort() function.


In [9]:
A = np.array([[4.99, 3.49, 9.99], [1.99, 9.99, 4.99], [14.99, 2.39, 7.29]])

print('Row ascending order =', np.sort(A, axis = 1))
print('Column ascending order =', np.sort(A, axis = 0))

Row ascending order = [[ 3.49  4.99  9.99]
 [ 1.99  4.99  9.99]
 [ 2.39  7.29 14.99]]
Column ascending order = [[ 1.99  2.39  4.99]
 [ 4.99  3.49  7.29]
 [14.99  9.99  9.99]]


#### Note:

The np.sort() function in NumPy is used to sort an array. It sorts the elements along a specified axis in ascending order by default.

## Exercise 4
#### Extract all elements from the following array with a value greater than 8 and print result to the console.

A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

In [12]:
A = np.array([[4.99, 3.49, 9.99], [1.99, 9.99, 4.99], [14.99, 2.39, 7.29]])

print(A[A > 8])

## Alternative for each element:
## for x in A:
##    print(x[x > 8])

[ 9.99  9.99 14.99]


#### Note:

    - x > 8 creates a boolean mask where True indicates the element is greater than 8 
    - x[x > 8] uses this boolean mask to filter and return the elements of x that are greater than 8.