## Exercise 1
#### The following array is given:

image = np.random.randint(low=0, high=256, size=(200, 300), dtype=np.uint8)

#### Sort this array along the rows in ascending order and assign to the variable image_sorted.

In [2]:
import numpy as np 

image = np.random.randint(low=0, high=256, size=(200, 300), dtype=np.uint8)

image_sorted = np.sort(image, axis = 1)

print(image_sorted)

[[  3   3   5 ... 254 254 255]
 [  1   2   3 ... 251 251 252]
 [  0   0   2 ... 252 252 253]
 ...
 [  0   1   2 ... 254 255 255]
 [  0   0   1 ... 253 254 255]
 [  0   1   2 ... 251 252 254]]


#### Note:

- The np.sort() function in NumPy is used to sort an array. Here’s a basic rundown of how it works:

- np.sort(a, axis=-1, kind=None, order=None)

## Exercise 2

#### The following array is given:

A = np.array([[4, 2, 1],
              [6, 4, 2]])


#### Expand this array by one dimension (add a new dimension at the beginning). 
#### Expected shape of the output array: (1, 2, 3).

#### In response, print array to the console.

Tip: Use the np.expand_dims() function.

In [6]:
A = np.array([[4, 2, 1], 
              [6, 4, 2]])

E2 = np.expand_dims(A, axis = 0)

print(E2.shape)
print(E2)

(1, 2, 3)
[[[4 2 1]
  [6 4 2]]]


#### Notes:

- The np.expand_dims() function in NumPy is used to expand the shape of an array by inserting a new axis at a specified position. This is often useful for adding a new dimension to an array, making it compatible with operations that require arrays of specific shapes.

- np.expand_dims(a, axis)

## Exercise 3
#### Using Numpy create a three-dimensional array called image with shape (200, 300, 3) filled with random values from 0 to 255 (inclusive) and data type np.uint8. Set random seed to 42.

#### In response, print array to the console.

In [8]:
np.random.seed(42)
image = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)

print(image)

[[[102 220 225]
  [ 95 179  61]
  [234 203  92]
  ...
  [ 41  27  87]
  [102 225  65]
  [170   0 238]]

 [[169 170 213]
  [159  44 250]
  [224 206  61]
  ...
  [162 118  77]
  [228  67  21]
  [ 68  30  64]]

 [[237  26 118]
  [ 62 157 198]
  [  1 151  37]
  ...
  [218 189  51]
  [193 250 243]
  [235  34 180]]

 ...

 [[116 102 228]
  [ 29  75  71]
  [156 133  53]
  ...
  [ 93  45  68]
  [124 238  76]
  [184 185 202]]

 [[216 202 116]
  [146 168 132]
  [236  80  45]
  ...
  [169 145 212]
  [123  50  70]
  [ 11  43  62]]

 [[ 32  52  65]
  [155   2  86]
  [ 83 240  27]
  ...
  [ 30  57 175]
  [ 72  83 171]
  [ 40 114 195]]]


## Exercise 4

#### The following array is given:

image = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)

#### Extend this array by one dimension (add a new dimension at the beginning) and assign to image_extended variable. Expected shape of this array is (1, 200, 300, 3).

Tip: Use the np.expand_dims() function.

In [10]:
image = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)

image_extended = np.expand_dims(image, axis = 0)

print(image_extended.shape)

(1, 200, 300, 3)
