## Exercise 1
#### The following array is given:

A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

#### Replace elements greater than 10 with a fixed value = 10.0 and print result to the console.

Tip: Use the np.where() function.

In [3]:
import numpy as np

A = np.array([[4.99, 3.49, 9.99], 
              [1.99, 9.99, 14.99], 
              [14.99, 2.39, 7.29]])

A1 = np.where(A > 10, 10.0, A)

print(A1)

[[ 4.99  3.49  9.99]
 [ 1.99  9.99 10.  ]
 [10.    2.39  7.29]]


#### Note:

1) np.where(A > 10, 10.0, A) creates a new array where each element is replaced by 10.0 if the element is greater than 10, otherwise it retains the original value.

2) This is done element-wise across the entire array.

## Exercise 2
#### Present the following two-dimensional array as a flattened one-dimensional array and print result to the console.

A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

Tip: Use the np.ravel() function.

In [4]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

print(np.ravel(A))

[ 4.99  3.49  9.99  1.99  9.99 14.99 14.99  2.39  7.29]


#### Note:

The np.ravel() function in NumPy is used to flatten a multi-dimensional array into a 1-dimensional array.

## Exercise 3
#### The following array is given:

A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

#### Using Numpy create an array of the same shape and data type as the given array and fill it with zeros. Print this array to the console.

Tip: Use the np.zeros_like() function.

In [6]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99], 
              [14.99, 2.39, 7.29]])

B = np.zeros_like(A)

print(B)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Note:

The np.zeros_like() function in NumPy is used to create a new array of zeros with the same shape and type as a given array. This can be very useful when you need an array initialized to zeros but want it to have the same dimensions and data type as an existing array.