## Exercise 1
#### The following array:



array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])


#### transform to the following:



array([[10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0]])


#### In response, print transformed array to the console.



Tip: Use the slice operator and assign the appropriate values.



In [2]:
import numpy as np

A = np.zeros((6,6))

A[::2, ::2] = 10
A[1::2, ::2] = 5

print(A)

[[10.  0. 10.  0. 10.  0.]
 [ 5.  0.  5.  0.  5.  0.]
 [10.  0. 10.  0. 10.  0.]
 [ 5.  0.  5.  0.  5.  0.]
 [10.  0. 10.  0. 10.  0.]
 [ 5.  0.  5.  0.  5.  0.]]


#### Notes:

1) A[::2, ::2] = 10: Sets every second element in both dimensions starting from (0,0) to 10.

2) A[1::2, ::2] = 5: Sets every second element in rows starting from 1 and every second element in columns starting from 0 to 5.

## Exercise 2
#### Combine the following arrays into one as shown below and print it to the console.

A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])


Tip: Use the np.append() function.

In [5]:
A = np.arange(12).reshape(-1, 4) 
B = np.array([[4, 3, 7, 2], [0, 5, 2, 6]])

C = np.append(A,B, axis = 0)

print(C)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 4  3  7  2]
 [ 0  5  2  6]]


#### Notes:

The np.append() function in NumPy is used to add values to the end of an array. It can append values along a specified axis of an array, or to a flattened version of the array if no axis is specified.

- Parameters:
    1) The array to which values will be appended.
    2) The values to be appended to the array.
    3) The axis along which to append the values. If None, both arr and values are flattened before use. Default is None.

## Exercise 3
#### The following arrays are given:

A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])      


#### Extract the same elements (intersection) of the arrays as a list and print result to the console.

Tip: Use the np.intersect1d() function.

In [6]:
A = np.arange(8).reshape(-1, 4) 
B = np.array([[9, 10, 11, 3], [2, 8, 0, 9]])

C = np.intersect1d(A, B) 

print(C)

[0 2 3]


#### Note:

The np.intersect1d() function in NumPy finds the intersection of two arrays, returning the sorted, unique values that are common to both input arrays. This is useful for identifying common elements in datasets.