## Exercise 1
#### The following array is given:

#### Starting with the second row of this array, randomly shuffle the rows and print result to the console.

Tip: Use the np.random.shuffle() function.

In [4]:
import numpy as np

A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])

np.random.shuffle(A[1:])

print(A)

[['id' 'price']
 ['001' '14.99']
 ['003' '7.99']
 ['004' '2.49']
 ['005' '1.49']
 ['002' '4.99']]


#### Note:

- np.random.shuffle will shuffle the rows starting from the second row (i.e., A[1:]), and the changes will be directly reflected in A. The print(A) statement will then display the shuffled array.

## Exercise 2

#### Return a list of indexes that sorts this array in ascending order and print it to the console.

Tip: Use the np.argsort() function.

In [6]:
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])

E2 = np.argsort(A)

print(E2)

[5 2 1 0 4 3]


#### Note:

- np.argsort() is a function that returns the indices that would sort an array. In other words, it provides the indices of the elements in a sorted order. This can be particularly useful when you want to sort an array but need to keep track of the original indices.

## Exercise 3

#### Round the values of this array to three decimal places and print result to the console.

Tip: Use the np.round() function.

In [9]:
np.random.seed(42)
A = np.random.randn(10, 8)

E3 = np.round(A, decimals = 3)

print(E3)

[[ 0.497 -0.138  0.648  1.523 -0.234 -0.234  1.579  0.767]
 [-0.469  0.543 -0.463 -0.466  0.242 -1.913 -1.725 -0.562]
 [-1.013  0.314 -0.908 -1.412  1.466 -0.226  0.068 -1.425]
 [-0.544  0.111 -1.151  0.376 -0.601 -0.292 -0.602  1.852]
 [-0.013 -1.058  0.823 -1.221  0.209 -1.96  -1.328  0.197]
 [ 0.738  0.171 -0.116 -0.301 -1.479 -0.72  -0.461  1.057]
 [ 0.344 -1.763  0.324 -0.385 -0.677  0.612  1.031  0.931]
 [-0.839 -0.309  0.331  0.976 -0.479 -0.186 -1.106 -1.196]
 [ 0.813  1.356 -0.072  1.004  0.362 -0.645  0.361  1.538]
 [-0.036  1.565 -2.62   0.822  0.087 -0.299  0.092 -1.988]]


#### Note:

- np.round() is a function in NumPy used to round elements of an array to the specified number of decimals. 

## Exercise 4
#### Calculate  the roots of the following polynomial:

#### In response, print these roots to the console.

Tip: Use the np.roots() function.

In [11]:
coefficients = [4, 5, 1]

roots = np.roots(coefficients)

print("Roots of the polynomial 4x^2 + 5x + 1:", roots)

Roots of the polynomial 4x^2 + 5x + 1: [-1.   -0.25]


#### Note:

- np.roots() is a function in NumPy that finds the roots of a polynomial with given coefficients.