## Exercise 1
#### The following array is given:

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### Using the slice operator, transform this array into the following:

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])

#### In response, print transformed array to the console.

In [3]:
import numpy as np

A = np.arange(12, dtype='int').reshape(-1, 4)

A = A[:, ::-1]

print(A)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


#### Notes:

- The first : means we are considering all rows.
- The ::-1 means we are reversing the order of the elements in each row.

## Exercise 2
#### The following  array is given:

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### Using the slice operator, transform this array into the following:

array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

In response, print transformed array to the console.

In [5]:
A = np.arange(12, dtype='int').reshape(-1, 4)

A = A[::-1, ::-1]

print(A)

[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


#### Notes:

- The first [::-1] means we are reversing the order of the rows.
- The second [::-1] means we are reversing the order of the columns in each row.

## Exercise 3
#### Random seed is set to 42. The following array is given:

image = np.random.randint(
    low=0, high=256, size=(10, 10, 3), dtype=np.uint8
)

Extract the first channel (index 0) of this image array and print it to the console.

In [8]:
np.random.seed(42)

image = np.random.randint(
    low=0, high=256, size=(10, 10, 3), dtype=np.uint8
)

image = image[:, :,0]

print(image)

[[102  95 234   3  14  46  99 212 188 153]
 [203 214 121 114 239 244  74  14 145 184]
 [116  85 226 235 151 181 160   6  52  14]
 [ 76 233 235 213  68 219 129   0 140 147]
 [ 20  46  19 209  57 156  86  24 235 110]
 [231 254 218 134 162  73 169  35 242 253]
 [187 249 201 231 189 116  49  74 189 158]
 [ 29   7  54 131 181 123 248 119 228  13]
 [ 50 155  40 120  72 115 167  85 131 242]
 [ 52 169  13 144 243 167   8  77  22  10]]


#### Notes:
- The first : means we are considering all rows (height) of the image.
- The second : means we are considering all columns (width) of the image.
- The 0 indicates that we are extracting the first slice.

## Exercise 4
#### The following array is given:

image = np.random.randint(
    low=0, high=256, size=(10, 10, 3), dtype=np.uint8
)

#### Extract any array of shape (5, 5, 3) from this array and assign to the result variable.

In [11]:
image = np.random.randint( low=0, high=256, size=(10, 10, 3), dtype=np.uint8 )

result = image[0:5, 0:5, :]

print(np.shape(result))

(5, 5, 3)


#### Notes:

- The first :5 means "take the first 5 rows".
- The second :5 means "take the first 5 columns".
- The third : means "take all".