## Exercise 1

#### The following arrays are given:

A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])


#### Concatenate these arrays as follows:

array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])

#### In response, print this array to the console.

Tip: Use the np.concatenate() function.

In [3]:
import numpy as np 

A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])

E1 = np.concatenate((A, B), axis = 0)

print(E1)

[[3 4 5]
 [8 3 1]
 [0 5 2]
 [4 2 1]]


#### Notes:

- np.concatenate is a function in the NumPy library used to join two or more arrays along a specified axis. It allows for the combination of arrays of the same shape (except in the dimension corresponding to the axis along which the arrays are concatenated). 

- (array1, array2, ...): A sequence of arrays to be concatenated.

- axis: The axis along which the arrays will be joined. The default is axis=0.

## Exercise 2
#### The following arrays are given:

data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])

#### Concatenate these arrays into one as shown below:

array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])

#### In response, print this array to the console.

In [4]:
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])

target = np.array([[0],
                   [1]])

E2 = np.concatenate((data, target), axis = 1)

print(E2)

[[4.3 4.2 0. ]
 [3.1 3.6 1. ]]


## Exercise 3
#### The following three one-dimensional arrays are given:

feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])


#### Transform each of these arrays into a column and concatenate them into one array as shown below. In response, print this array to the console.

Tip: Use the np.column_stack() function.

In [8]:
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])

E3 = np.column_stack((feature1, feature2, feature3))

print(E3)

[[1.6 0.4 1.4]
 [0.9 1.3 0.3]
 [2.2 3.2 1.2]]


#### Note:

np.column_stack is a function in the NumPy library that stacks 1-D arrays as columns into a 2-D array. It is particularly useful when you want to combine multiple 1-D arrays into a 2-D array by aligning them as columns.