## Exercise 1
#### Using Numpy create and convert the following array into the list:



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])


#### In response, print list to the console.



Tip: Use the np.array.tolist() method.

In [3]:
import numpy as np

A = np.arange(12).reshape(-1,4)

A_List = A.tolist()

print(A_List)

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


#### Note:

The tolist() method in NumPy is used to convert a NumPy array into a nested Python list. Each element of the array is converted to the corresponding Python type (e.g., NumPy's int64 to Python's int).

## Exercise 2
#### The following array is given:



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])


#### Using the slice operator, transform this array into the following:



array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])


#### In response, print transformed array to the console.



In [4]:
A_sliced = A[::-1]
print(A_sliced)

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


#### Note:

1) sequence[start:stop:step]

2) The slice [::-1] in Python is used to reverse a sequence. This works for lists, tuples, strings, and NumPy arrays. When applied to a NumPy array, it reverses the order of the elements along a specified axis.

## Exercise 3
#### The following array:



array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])


#### transform to this array:



array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])


#### In response, print transformed array to the console.



Tip: Use the np.pad() function.

In [8]:
B = np.array([[1., 1., 1., 1.], [1., 1., 1., 1.], [1., 1., 1., 1.], [1., 1., 1., 1.]])


B_pad = np.pad(B, pad_width = 1)
print (B_pad)


## Could also use the following to create B --> B = np.ones(shape=(4, 4))

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### Note:
The np.pad() function in NumPy is used to pad an array with a specified constant, edge, or custom values. 