## Exercise 1
#### The following arrays are given.

#### Calculate arithmetic means of these arrays (elementwise) and print result to the console.

In [2]:
import numpy as np


A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])

E1 = np.divide(np.add(A, B), 2)

print(E1)

[[3.5 3.5 5.5 3.5]
 [5.5 3.  1.5 5.5]]


## Exercise 2
#### The following arrays are given:

#### Multiply these arrays (elementwise) and print result to the console.

In [3]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])

E2 = np.multiply(A,B)

print(E2)

[[12 12 18 10]
 [30  9  2 30]]


## Exercise 3
#### The following array is given:

#### Calculate the square root of each element of this array and print result to the console.

Tip: Use the np.sqrt() function.

In [4]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])

E3 = np.sqrt(A)

print(E3)

[[1.73205081 2.         3.         1.41421356]
 [2.23606798 1.73205081 1.41421356 2.23606798]]
