## Exercise 1
#### Using Numpy create the following two-dimensional array:

[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]


Print result to the console as shown below.

In [3]:
import numpy as np

array1 = np.arange(1, 6, 1, dtype=int)

array2 = np.diag(array1, k = 0)

print(array2)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#### Note:
np.diag() is a function in the NumPy library that is used to either extract a diagonal from a matrix or create a diagonal matrix. 

## Exercise 2
#### Using Numpy create the following array:

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])


#### Save this array to a binary file named 'array.npy' and then load that file back into another variable. Print this variable to the console.

Tip: Use the np.save() and np.load() functions.

In [8]:
array3 = np.ndarray.reshape(np.arange(12), (3,4))

np.save('array.npy', array3)

array4 = np.load('array.npy')

print(array4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


#### Notes:

1) np.save() is a function in the NumPy library used to save an array to a binary file in .npy format. This format is efficient for storing NumPy arrays, ensuring that the array's data and metadata (like dtype and shape) are preserved accurately.

2) np.load() is a function in the NumPy library used to load arrays or pickled objects from files stored in .npy or .npz formats.

## Exercise 3
#### Using Numpy create the following array:

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### Save this array to a text file named 'array.txt' with two decimal places and then load this file back into another variable. Print this variable to the console.

Tip: Use the np.savetxt() and np.loadtxt() functions.

In [10]:
A = np.arange(12).reshape(-1, 4)

np.savetxt(fname='array.txt', X=A, fmt='%0.2f')

Atext = np.loadtxt('array.txt')

print(Atext)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


#### Notes:

1) np.savetxt() is a function in the NumPy library used to save an array to a text file. This function is particularly useful for exporting data in a human-readable format, such as CSV or TSV.

2) np.loadtxt() is a function in the NumPy library used to load data from a text file. This function is particularly useful for reading numerical data from CSV, TSV, or other delimited text files into a NumPy array.