## Exercise 1
#### The following array is given:

#### Calculate the new column: the difference between the highest and lowest price.

#### Steps:

- Assign the calculated difference to the max_min_diff variable

- Add the calculated column (variable max_min_diff) to the array playway_values at the end.

#### In response, print result to the console.

In [6]:
import numpy as np


np.set_printoptions(suppress=True)
playway_values = np.array(
    [
        [305.0, 324.5, 283.5, 310.0, 64081.0],
        [325.5, 340.5, 320.0, 340.5, 55496.0],
        [324.0, 340.5, 315.0, 330.0, 36152.0],
        [344.0, 344.0, 310.0, 315.0, 35992.0],
        [306.5, 307.0, 291.0, 305.0, 32539.0],
        [274.0, 291.0, 250.0, 258.0, 79402.0],
        [278.0, 284.5, 256.0, 264.0, 35700.0],
        [270.0, 270.0, 238.5, 245.0, 60445.0],
        [218.0, 228.0, 196.0, 197.0, 94031.0],
        [210.0, 229.0, 198.8, 211.0, 100412.0],
        [205.0, 248.0, 197.8, 240.5, 50659.0],
        [245.0, 269.0, 232.5, 264.0, 99480.0],
        [264.0, 280.0, 251.0, 270.0, 70136.0],
        [267.0, 280.0, 267.0, 279.5, 30732.0],
        [297.5, 307.0, 280.0, 280.5, 43426.0],
        [274.0, 289.0, 258.0, 285.0, 37098.0],
        [305.0, 309.0, 296.5, 309.0, 31939.0],
        [313.0, 330.0, 295.0, 304.0, 46724.0],
        [300.0, 309.0, 295.5, 300.0, 27213.0],
        [302.0, 306.5, 290.0, 296.0, 13466.0],
        [299.0, 300.0, 287.0, 300.0, 10316.0],
        [302.5, 309.0, 302.0, 306.5, 15698.0],
    ]
)

max_min_diff = playway_values[:,1] - playway_values[:,2] ## Using slicing to minus the High by the low, thus the difference.

max_min_diff = max_min_diff.reshape(22,1) ## Reshaping to a 2D Array so I can append it to the original

playway_values = np.append(playway_values, max_min_diff, axis = 1) ## Apending by adding a column to the end.
print(playway_values)

[[   305.     324.5    283.5    310.   64081.      41. ]
 [   325.5    340.5    320.     340.5  55496.      20.5]
 [   324.     340.5    315.     330.   36152.      25.5]
 [   344.     344.     310.     315.   35992.      34. ]
 [   306.5    307.     291.     305.   32539.      16. ]
 [   274.     291.     250.     258.   79402.      41. ]
 [   278.     284.5    256.     264.   35700.      28.5]
 [   270.     270.     238.5    245.   60445.      31.5]
 [   218.     228.     196.     197.   94031.      32. ]
 [   210.     229.     198.8    211.  100412.      30.2]
 [   205.     248.     197.8    240.5  50659.      50.2]
 [   245.     269.     232.5    264.   99480.      36.5]
 [   264.     280.     251.     270.   70136.      29. ]
 [   267.     280.     267.     279.5  30732.      13. ]
 [   297.5    307.     280.     280.5  43426.      27. ]
 [   274.     289.     258.     285.   37098.      31. ]
 [   305.     309.     296.5    309.   31939.      12.5]
 [   313.     330.     295.    

#### Note:

- Could have also used playway_values = np.concatenate((playway_values, max_min_diff), axis=1)

## Exercise 2
#### The following array is given:

#### Extract rows from this array where closing price (column with index 3) is greater than 300.0. In response, print result to the console.

In [13]:

np.set_printoptions(suppress=True)
playway_values = np.array(
    [
        [305.0, 324.5, 283.5, 310.0, 64081.0, 41.0],
        [325.5, 340.5, 320.0, 340.5, 55496.0, 20.5],
        [324.0, 340.5, 315.0, 330.0, 36152.0, 25.5],
        [344.0, 344.0, 310.0, 315.0, 35992.0, 34.0],
        [306.5, 307.0, 291.0, 305.0, 32539.0, 16.0],
        [274.0, 291.0, 250.0, 258.0, 79402.0, 41.0],
        [278.0, 284.5, 256.0, 264.0, 35700.0, 28.5],
        [270.0, 270.0, 238.5, 245.0, 60445.0, 31.5],
        [218.0, 228.0, 196.0, 197.0, 94031.0, 32.0],
        [210.0, 229.0, 198.8, 211.0, 100412.0, 30.2],
        [205.0, 248.0, 197.8, 240.5, 50659.0, 50.2],
        [245.0, 269.0, 232.5, 264.0, 99480.0, 36.5],
        [264.0, 280.0, 251.0, 270.0, 70136.0, 29.0],
        [267.0, 280.0, 267.0, 279.5, 30732.0, 13.0],
        [297.5, 307.0, 280.0, 280.5, 43426.0, 27.0],
        [274.0, 289.0, 258.0, 285.0, 37098.0, 31.0],
        [305.0, 309.0, 296.5, 309.0, 31939.0, 12.5],
        [313.0, 330.0, 295.0, 304.0, 46724.0, 35.0],
        [300.0, 309.0, 295.5, 300.0, 27213.0, 13.5],
        [302.0, 306.5, 290.0, 296.0, 13466.0, 16.5],
        [299.0, 300.0, 287.0, 300.0, 10316.0, 13.0],
        [302.5, 309.0, 302.0, 306.5, 15698.0, 7.0],
    ]
)

E2 = playway_values[playway_values[:, 3] > 300]

print(E2)

[[  305.    324.5   283.5   310.  64081.     41. ]
 [  325.5   340.5   320.    340.5 55496.     20.5]
 [  324.    340.5   315.    330.  36152.     25.5]
 [  344.    344.    310.    315.  35992.     34. ]
 [  306.5   307.    291.    305.  32539.     16. ]
 [  305.    309.    296.5   309.  31939.     12.5]
 [  313.    330.    295.    304.  46724.     35. ]
 [  302.5   309.    302.    306.5 15698.      7. ]]


#### Notes:

- playway_values[:, 3] > 300 creates a boolean array where each element is True if the corresponding value in the fourth column is greater than 300 and False otherwise.
- playway_values[playway_values[:, 3] > 300] uses this boolean array to index the original array, returning only the rows where the condition is True.

## Exercise 3
#### The following array is given:

#### From this array extract the first 10 rows with the highest volume sorted in descending order.



In [18]:
np.set_printoptions(suppress=True)
playway_values = np.array(
    [
        [305.0, 324.5, 283.5, 310.0, 64081.0, 41.0],
        [325.5, 340.5, 320.0, 340.5, 55496.0, 20.5],
        [324.0, 340.5, 315.0, 330.0, 36152.0, 25.5],
        [344.0, 344.0, 310.0, 315.0, 35992.0, 34.0],
        [306.5, 307.0, 291.0, 305.0, 32539.0, 16.0],
        [274.0, 291.0, 250.0, 258.0, 79402.0, 41.0],
        [278.0, 284.5, 256.0, 264.0, 35700.0, 28.5],
        [270.0, 270.0, 238.5, 245.0, 60445.0, 31.5],
        [218.0, 228.0, 196.0, 197.0, 94031.0, 32.0],
        [210.0, 229.0, 198.8, 211.0, 100412.0, 30.2],
        [205.0, 248.0, 197.8, 240.5, 50659.0, 50.2],
        [245.0, 269.0, 232.5, 264.0, 99480.0, 36.5],
        [264.0, 280.0, 251.0, 270.0, 70136.0, 29.0],
        [267.0, 280.0, 267.0, 279.5, 30732.0, 13.0],
        [297.5, 307.0, 280.0, 280.5, 43426.0, 27.0],
        [274.0, 289.0, 258.0, 285.0, 37098.0, 31.0],
        [305.0, 309.0, 296.5, 309.0, 31939.0, 12.5],
        [313.0, 330.0, 295.0, 304.0, 46724.0, 35.0],
        [300.0, 309.0, 295.5, 300.0, 27213.0, 13.5],
        [302.0, 306.5, 290.0, 296.0, 13466.0, 16.5],
        [299.0, 300.0, 287.0, 300.0, 10316.0, 13.0],
        [302.5, 309.0, 302.0, 306.5, 15698.0, 7.0],
    ]
)

sorted_indices = np.argsort(playway_values[:, 4])

E3 = playway_values[sorted_indices[::-1]]

E3 = E3[0:10,:]

print(E3)

[[   210.     229.     198.8    211.  100412.      30.2]
 [   245.     269.     232.5    264.   99480.      36.5]
 [   218.     228.     196.     197.   94031.      32. ]
 [   274.     291.     250.     258.   79402.      41. ]
 [   264.     280.     251.     270.   70136.      29. ]
 [   305.     324.5    283.5    310.   64081.      41. ]
 [   270.     270.     238.5    245.   60445.      31.5]
 [   325.5    340.5    320.     340.5  55496.      20.5]
 [   205.     248.     197.8    240.5  50659.      50.2]
 [   313.     330.     295.     304.   46724.      35. ]]


#### Notes:

- Calculates the indices that would sort the array playway_values based on the values in the fifth column (index 4).
- Reorders the rows of playway_values in descending order based on the previously calculated sorted indices. The [::-1] part reverses the order to achieve descending sorting.
- The np.argsort() function returns the indices that would sort an array. It does not return the sorted values directly; instead, it returns the indices of the elements in the array in sorted order.

## Exercise 4
#### The following array is given:

#### Add to this array column that returns 1 in case the close price is higher than the open price, otherwise 0.

In [24]:
np.set_printoptions(suppress=True)
playway_values = np.array(
    [
        [305.0, 324.5, 283.5, 310.0, 64081.0, 41.0],
        [325.5, 340.5, 320.0, 340.5, 55496.0, 20.5],
        [324.0, 340.5, 315.0, 330.0, 36152.0, 25.5],
        [344.0, 344.0, 310.0, 315.0, 35992.0, 34.0],
        [306.5, 307.0, 291.0, 305.0, 32539.0, 16.0],
        [274.0, 291.0, 250.0, 258.0, 79402.0, 41.0],
        [278.0, 284.5, 256.0, 264.0, 35700.0, 28.5],
        [270.0, 270.0, 238.5, 245.0, 60445.0, 31.5],
        [218.0, 228.0, 196.0, 197.0, 94031.0, 32.0],
        [210.0, 229.0, 198.8, 211.0, 100412.0, 30.2],
        [205.0, 248.0, 197.8, 240.5, 50659.0, 50.2],
        [245.0, 269.0, 232.5, 264.0, 99480.0, 36.5],
        [264.0, 280.0, 251.0, 270.0, 70136.0, 29.0],
        [267.0, 280.0, 267.0, 279.5, 30732.0, 13.0],
        [297.5, 307.0, 280.0, 280.5, 43426.0, 27.0],
        [274.0, 289.0, 258.0, 285.0, 37098.0, 31.0],
        [305.0, 309.0, 296.5, 309.0, 31939.0, 12.5],
        [313.0, 330.0, 295.0, 304.0, 46724.0, 35.0],
        [300.0, 309.0, 295.5, 300.0, 27213.0, 13.5],
        [302.0, 306.5, 290.0, 296.0, 13466.0, 16.5],
        [299.0, 300.0, 287.0, 300.0, 10316.0, 13.0],
        [302.5, 309.0, 302.0, 306.5, 15698.0, 7.0],
    ]
)

results = [1 if row[3] > row[0] else 0 for row in playway_values]

results_array = np.array(results).reshape(-1, 1)

E4 = np.concatenate((playway_values, results_array), axis = 1)

print(E4)

[[   305.     324.5    283.5    310.   64081.      41.       1. ]
 [   325.5    340.5    320.     340.5  55496.      20.5      1. ]
 [   324.     340.5    315.     330.   36152.      25.5      1. ]
 [   344.     344.     310.     315.   35992.      34.       0. ]
 [   306.5    307.     291.     305.   32539.      16.       0. ]
 [   274.     291.     250.     258.   79402.      41.       0. ]
 [   278.     284.5    256.     264.   35700.      28.5      0. ]
 [   270.     270.     238.5    245.   60445.      31.5      0. ]
 [   218.     228.     196.     197.   94031.      32.       0. ]
 [   210.     229.     198.8    211.  100412.      30.2      1. ]
 [   205.     248.     197.8    240.5  50659.      50.2      1. ]
 [   245.     269.     232.5    264.   99480.      36.5      1. ]
 [   264.     280.     251.     270.   70136.      29.       1. ]
 [   267.     280.     267.     279.5  30732.      13.       1. ]
 [   297.5    307.     280.     280.5  43426.      27.       0. ]
 [   274. 

#### Notes:

- Creates a list results where each element is 1 if the value in the fourth column of a row is greater than the value in the first column of the same row, and 0 otherwise.
- Converts to numpy array so it can be concatenated as a last column. (Remember the '-1' means any number of rows in (-1,1)).
- Can also use: flag = playway_values[:, [0]] < playway_values[:, [3]]
   - This creates a boolean array which you can then turn into a 1 or 0 via astype(int).